#!/bin/sh

set -e

#defining list of packages to install
apt_packages="curl man git python3-pip ripgrep tmux zsh vim"

#install packages using APT package manager
echo -e  "\n Installing Packages"
sudo apt-get update && sudo apt-get install -y ${apt_packages}

#clone dotfiles
echo -e "\n Cloning Dotfiles" 
git clone https://github.com/neongulfbaul/dotfiles "$HOME/.dotfiles/"

#create initial directories
echo -e "\n Creating Directories"
mkdir -p "${HOME}/.config/zsh"
mkdir -p "${HOME}/.cache/zsh"
mkdir -p "${HOME}/.local/share"

# create symlinks
echo -e "\n Creating Symlinks"

ln -fs "$HOME/.dotfiles/zsh/main.zsh" "$HOME/.zshenv" 
ln -fs "$HOME/.dotfiles/.vimrc" "$HOME/.vimrc"
ln -fs "$HOME/.dotfiles/.tmux.conf" "$HOME/.tmux.conf"
ln -fs "$HOME/.dotfiles/zsh/login.zsh" "$HOME/.config/zsh/.zlogin"
ln -fs "$HOME/.dotfiles/zsh/logout.zsh" "$HOME/.config/zsh/.zlogout"
ln -fs "$HOME/.dotfiles/zsh/profile.zsh" "$HOME/.config/zsh/.zprofile"
ln -fs "$HOME/.dotfiles/zsh/env.zsh" "$HOME/.config/zsh/.zshenv"
ln -fs "$HOME/.dotfiles/zsh/rc.zsh" "$HOME/.config/zsh/.zshrc"

# recursive cp for the rest as they don't need renaming
cp -rsf "$HOME/.dotfiles/zsh/config" "$HOME/.config/zsh/config"
cp -rsf "$HOME/.dotfiles/zsh/lib" "$HOME/.config/zsh/lib"
cp -rsf "$HOME/.dotfiles/zsh/pkgs" "$HOME/.config/zsh/pkgs"

# install zsh plugins
source ~"$HOME/.dotfiles/zsh/lib/plugins-base.zsh"

# install plug (vim plugin manager)
curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#install tmux plugin manager(tpm)
git clone --depth 1 https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"

# change default shell to zsh
echo -e "\n Changing default shell"
chsh -s "$(command -v zsh)"

# install tmux plugins
printf "\n\nInstalling tmux plugins...\n"
export TMUX_PLUGIN_MANAGER_PATH="${HOME}/.tmux/plugins"
"${HOME}/.tmux/plugins/tpm/bin/install_plugins"

# Install Vim plugins
printf "\n\nInstalling Vim plugins...\n"
vim -E +PlugInstall +qall || true

# done
zsh

echo -e "\n done"

exit 0
