#!/bin/sh

set -e

#defining list of packages to install
apt_packages="curl man git python3-pip ripgrep tmux zsh vim"

#install packages using APT package manager
echo -e  "\n Installing Packages"
sudo apt-get update && sudo apt-get install -y ${apt_packages}

#clone dotfiles
echo -e "\n Cloning Dotfiles" 
git clone https://github.com/neongulfbaul/dotfiles "$HOME/.dotfiles/"

#create initial directories
echo -e "\n Creating Directories"
mkdir -p "${HOME}/.config/zsh"
mkdir -p "${HOME}/.cache/zsh"
mkdir -p "${HOME}/.local/share"

# cp dots
echo -e "\n Copying dots"

cp "$HOME/.dotfiles/zsh/main.zsh" "$HOME/.zshrc" 
cp "$HOME/.dotfiles/zsh/env.zsh" "$HOME/.config/zsh/.zshenv"
cp "$HOME/.dotfiles/zsh/rc.zsh" "$HOME/.config/zsh/.zshrc"
cp "$HOME/.dotfiles/.vimrc" "$HOME/.vimrc"
cp "$HOME/.dotfiles/.tmux.conf" "$HOME/.tmux.conf"

# recursive cp for the remaining folders 
cp -r "$HOME/.dotfiles/zsh/config" "$HOME/.config/zsh/config"
cp -r "$HOME/.dotfiles/zsh/lib" "$HOME/.config/zsh/lib"
cp -r "$HOME/.dotfiles/zsh/pkgs" "$HOME/.config/zsh/pkgs"

# install plug (vim plugin manager)
curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#install tmux plugin manager(tpm)
git clone --depth 1 https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"

# install tmux plugins
printf "\n Installing tmux plugins...\n"
export TMUX_PLUGIN_MANAGER_PATH="${HOME}/.tmux/plugins"
"${HOME}/.tmux/plugins/tpm/bin/install_plugins"

# Install Vim plugins
printf "\n\nInstalling Vim plugins...\n"
vim -E +PlugInstall +qall || true 

printf "\n\changing default shell\n"
#changing default shell
#chsh -s "$(command -v zsh)"

# done
zsh

echo -e "\n done"

exit 0
