# ZSH Home Manager Module
{ config, lib, pkgs, ... }:

{
      home.file.".config/zsh/".source = ../../config/zsh;
      home.file.".config/zsh/".recursive = true;

      programs.zsh = {
        enable = true;
        autocd = false;
        dotDir = ".config/zsh";
        enableCompletion = true;
        history.path = "$ZDODIR/zsh_history";
        envExtra = ''
        # This file is autogenerated, do not edit it!

        # Be more restrictive with permissions in $HOME; no one has any business
        # reading things that don't belong to them.
        if (( EUID != 0 )); then
          umask 027
        else
          # Be even less permissive if root.
          umask 077
        fi
            '';
        initExtraBeforeCompInit = ''
           source $ZDOTDIR/config.zsh
           source $ZDOTDIR/completion.zsh
            '';
        completionInit = ''
          # Only generate the dump if it doesn't exist. `hey reload` will clear it. And
          # yes, -d is necessary. compinit doesn't respect cache-path.
          ZCOMPCACHE="$XDG_CACHE_HOME/zsh/zcompdump.$ZSH_VERSION"
          if autoload -Uz compinit; then
            compinit -u -C -d "$ZCOMPCACHE"
            [[ ! -f "$ZCOMPCACHE.zwc" && -f $ZCOMPCACHE ]] && zcompile "$ZCOMPCACHE"
          fi 
          '';
        initExtra = ''
          source $ZDOTDIR/aliases.zsh
          source $ZDOTDIR/keybinds.zsh
          source $ZDOTDIR/p10k.zsh
          unset ZSH_AUTOSUGGEST_USE_ASYNC
            '';

      };  
      programs.fzf = {
        enable = true;
        enableZshIntegration = true;
      };

  #xdg.configFile."zsh/.zshenv".source = ./zshenv;
  #xdg.configFile."zsh/.zshrc".source = ./zshrc;
  #home.file.".config/zsh/scripts".source = ./files/scripts;
  #home.file.".config/zsh/scripts".recursive = true;
}
