# modules/shell/zsh.nix
{ lib, config, pkgs, ... }:
let
  inherit (lib) mkEnableOption mkIf types concatMapStringsSep;
  cfg = config.modules.shell.zsh;
in {
  options.modules.shell.zsh = {
    enable   = mkEnableOption "zsh";
    rcInit   = lib.mkOption { type = types.lines; default = ""; };
    envInit  = lib.mkOption { type = types.lines; default = ""; };
    rcFiles  = lib.mkOption { type = types.listOf (types.either types.str types.path); default = []; };
    envFiles = lib.mkOption { type = types.listOf (types.either types.str types.path); default = []; };
  };

  config = mkIf cfg.enable {

    # ── System level ──────────────────────────────────────────────
    # Just wires zsh into NixOS — no config generation
    programs.zsh = {
      enable               = true;
      enableCompletion     = true;
      enableGlobalCompInit = false;  # we handle compinit ourselves
      promptInit           = "";     # we handle prompt ourselves
      histFile             = "$XDG_STATE_HOME/zsh/history";
      enableLsColors       = false;
    };

    users.defaultUserShell = pkgs.zsh;

    environment.variables = {
      ZDOTDIR       = "$XDG_CONFIG_HOME/zsh";
      ZGEN_DIR      = "$XDG_DATA_HOME/zgenom";
      _FASD_DATA    = "$XDG_CACHE_HOME/fasd";
    };

    systemd.user.tmpfiles.rules = [
      "d %h/.cache/zsh       750 - - - -"
      "d %h/.local/state/zsh 700 - - - -"
    ];

    # ── Files (via home.nix aliases) ──────────────────────────────
    home.configFile = {
      # Link your whole config/zsh dir — individual generated files
      # below will coexist since they're explicit keys not a dir symlink
      "zsh/config.zsh".source     = ../../config/zsh/config.zsh;
      "zsh/aliases.zsh".source    = ../../config/zsh/aliases.zsh;
      "zsh/keybinds.zsh".source   = ../../config/zsh/keybinds.zsh;
      "zsh/completion.zsh".source = ../../config/zsh/completion.zsh;
      "zsh/p10k.zsh".source       = ../../config/zsh/p10k.zsh;

      # Generated .zshrc — sources your config files in order
      # This replaces HM's programs.zsh initContent
      "zsh/.zshrc".text = ''
        # autogenerated — edit zsh.nix or config/zsh/*.zsh instead
        source $ZDOTDIR/config.zsh
        source $ZDOTDIR/aliases.zsh
        source $ZDOTDIR/keybinds.zsh
        [[ ! -f $ZDOTDIR/completion.zsh ]] || source $ZDOTDIR/completion.zsh
        [[ ! -f $ZDOTDIR/p10k.zsh ]]      || source $ZDOTDIR/p10k.zsh
        ${cfg.rcInit}
        ${concatMapStringsSep "\n" builtins.readFile cfg.rcFiles}
      '';

      # Generated .zshenv — sets umask + envInit escape hatch
      "zsh/.zshenv".text = ''
        # autogenerated — edit zsh.nix or set modules.shell.zsh.envInit
        if (( EUID != 0 )); then umask 027; else umask 077; fi
        ${cfg.envInit}
        ${concatMapStringsSep "\n" builtins.readFile cfg.envFiles}
      '';
    };

    # Cleanup hook — nukes zgenom state on rebuild so it regenerates
    home.file.".local/share/zgenom/.keep".text = "";  # ensure dir exists
  };
}
