# modul# modules/shell/zsh.nix
{ lib, config, pkgs, ... }:
let
  inherit (lib) mkEnableOption mkIf types concatMapStringsSep mkDefault mkMerge;
  cfg = config.modules.shell.zsh;
in {
  options.modules.shell.zsh = {
    enable   = mkEnableOption "zsh";
    rcInit   = lib.mkOption { type = types.lines; default = ""; };
    envInit  = lib.mkOption { type = types.lines; default = ""; };
    rcFiles  = lib.mkOption { type = types.listOf (types.either types.str types.path); default = []; };
    envFiles = lib.mkOption { type = types.listOf (types.either types.str types.path); default = []; };
  };

  config = mkMerge [
    # 1. Global Default (Opt-In Guard)
    { modules.shell.zsh.enable = mkDefault false; }

    # 2. The Actual Logic
    (mkIf cfg.enable {
      # ── System level ──────────────────────────────────────────────
      programs.zsh = {
        enable               = true;
        enableCompletion     = true;
        enableGlobalCompInit = false;  # we handle compinit ourselves
        promptInit           = "";      # we handle prompt ourselves
        histFile             = "$XDG_STATE_HOME/zsh/history";
        enableLsColors       = false;
      };

      users.defaultUserShell = pkgs.zsh;

      user.packages = with pkgs; [
        at
        bat      # a better cat
        bc
        dust     # a better du
        eza      # a better ls
        fasd
        fd
        fzf
        gnumake
        libqalculate  # calculator cli w/ currency conversion
        nix-zsh-completions
        ripgrep  # a better grep
        tokei    # for code statistics
        unar
        zip
        unzip
        tree
      ];

      environment.variables = {
        ZDOTDIR       = "$XDG_CONFIG_HOME/zsh";
        ZGEN_DIR      = "$XDG_DATA_HOME/zgenom";
        _FASD_DATA    = "$XDG_CACHE_HOME/fasd";
        SUDO_PROMPT = "\x1b[1;38;2;205;214;244;48;2;49;50;68msudo\x1b[0m \x1b[38;2;148;226;213m%%u\x1b[0m@\x1b[38;2;137;180;250m%%h\x1b[0m: ";
      };

      systemd.user.tmpfiles.rules = [
        "d %h/.cache/zsh       750 - - - -"
        "d %h/.local/state/zsh 700 - - - -"
      ];

      # ── Files (via home.nix aliases) ──────────────────────────────
      home.configFile = {
        "zsh/config.zsh".source     = ../../config/zsh/config.zsh;
        "zsh/aliases.zsh".source    = ../../config/zsh/aliases.zsh;
        "zsh/keybinds.zsh".source   = ../../config/zsh/keybinds.zsh;
        "zsh/completion.zsh".source = ../../config/zsh/completion.zsh;
        "zsh/p10k.zsh".source       = ../../config/zsh/p10k.zsh;

        "zsh/.zshrc".text = ''
          # autogenerated — edit zsh.nix or config/zsh/*.zsh instead
          source $ZDOTDIR/config.zsh
          source $ZDOTDIR/aliases.zsh
          source $ZDOTDIR/keybinds.zsh
          [[ ! -f $ZDOTDIR/completion.zsh ]] || source $ZDOTDIR/completion.zsh
          [[ ! -f $ZDOTDIR/p10k.zsh ]]      || source $ZDOTDIR/p10k.zsh
          ${cfg.rcInit}
          ${concatMapStringsSep "\n" builtins.readFile cfg.rcFiles}
        '';

        "zsh/.zshenv".text = ''
          # autogenerated — edit zsh.nix or set modules.shell.zsh.envInit
          if (( EUID != 0 )); then umask 027; else umask 077; fi
          ${cfg.envInit}
          ${concatMapStringsSep "\n" builtins.readFile cfg.envFiles}
        '';
      };
    })
  ];
}
